# Generated by Django 4.1.1 on 2023-04-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=244)),
                ('last_name', models.CharField(default='', max_length=244)),
                ('phone', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='', max_length=45)),
                ('email', models.EmailField(max_length=244)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='media/uploads/profile/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
